POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1paWtrYTEiLCJpZCI6IjY4OTNhZGViOTM4NjNiMjUyZjE5Yjg0OCIsImlhdCI6MTc1NDUwOTExMn0.E5YTUezUrJWMQFayQQDUO-Hc9yeFNaLMTrLiCzco1cM

{
  "content": "Tämä on testi joka myös sitten toimii",
  "important": true
}